import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My best app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">

        <header className="p-4 border-b">
          <nav className="flex gap-4">
            <Link href="/">Home</Link> 
            <Link href="/about">about</Link>        
          </nav>
        </header>
      
      <main className="flex-1 p-8">
        {children}
      </main>
      
      <footer className="p-4 border-t text-sm">
          analist AI &copy; 2025
      </footer>
      
      </body>
    </html>
  );
}
